const possibleAudio = {
  success: [
    'audio/success.mp3',
    'audio/success-2.mp3',
    'audio/success-3.mp3',
    'audio/success-4.mp3',
    'audio/success-5.mp3',
    'audio/success-6.mp3',
    'audio/success-7.mp3',
    'audio/success-8.mp3',
    'audio/success-9.mp3',
    'audio/success-10.mp3',
    'audio/success-11.mp3',
    'audio/success-12.mp3',
    'audio/success-13.mp3',
    'audio/success-14-violin.mp3',
    'audio/success-15-violin.mp3',
    'audio/success-16-violin.mp3',
    'audio/success-17-violin.mp3',
    'audio/success-18-violin.mp3',
    'audio/success-19-violin.mp3',
    'audio/success-20-violin.mp3',
    'audio/success-21-violin.mp3',
    'audio/success-22-violin.mp3',
    'audio/success-23-violin.mp3',
    'audio/success-24-violin.mp3',
    'audio/success-25-violin.mp3',
    'audio/success-26-violin.mp3',
    'audio/success-27-violin.mp3',
    'audio/success-28-violin.mp3',
    'audio/success-29-violin.mp3',
    'audio/success-30-violin.mp3',
    'audio/success-31-violin.mp3',
    'audio/success-32-violin.mp3',
    'audio/success-33-violin.mp3',
    'audio/success-34-violin.mp3',
    'audio/success-35-violin.mp3',
    'audio/success-36-violin.mp3',
    'audio/success-37-violin.mp3',
    'audio/success-38-violin.mp3',
    'audio/success-39-violin.mp3',
    'audio/success-40-violin.mp3',
    'audio/success-41-violin-long.mp3',
    'audio/success-42-violin.mp3',
    'audio/success-43-violin.mp3',
    'audio/success-44-violin.mp3',
    'audio/success-45-violin.mp3',
    'audio/success-46-violin.mp3',
    'audio/success-47-violin.mp3',
    'audio/success-48-violin.mp3',
    'audio/success-49-violin.mp3',
    'audio/success-50-violin.mp3',
  ],
  fail: [
    'audio/fail.mp3',
    'audio/fail-2.mp3',
    'audio/fail-3.mp3',
    'audio/fail-4.mp3',
    'audio/fail-5.mp3',
    'audio/fail-6.mp3',
    'audio/fail-7.mp3',
    'audio/fail-8-people.mp3',
    'audio/fail-9-funny.mp3',
    'audio/fail-10.mp3',
    'audio/fail-11.mp3',
    'audio/fail-12.mp3',
    'audio/fail-13.mp3',
    'audio/fail-14.mp3',
    'audio/fail-15.mp3',
    'audio/fail-16.mp3',
    'audio/fail-17-people.mp3',
    'audio/fail-18.mp3',
    'audio/fail-19.mp3',
    'audio/fail-20.mp3',
    'audio/fail-21.mp3',
    'audio/fail-22.mp3',
    'audio/fail-23.mp3',
    'audio/fail-24.mp3',
    'audio/fail-25-cat.mp3',
    'audio/fail-26-cat.mp3',
    'audio/fail-27.mp3',
    'audio/fail-28.mp3',
    'audio/fail-29.mp3',
    'audio/fail-30.mp3',
    'audio/fail-31.mp3',
    'audio/fail-32.mp3',
    'audio/fail-33.mp3',
    'audio/fail-34.mp3',
    'audio/fail-35.mp3',
    // 'audio/fail-36.mp3',
    'audio/fail-37-long.mp3',
    // 'audio/fail-38.mp3',
    'audio/fail-39.mp3',
    'audio/fail-40.mp3',
    'audio/fail-41.mp3',
    'audio/fail-42.mp3',
    'audio/fail-43.mp3',
    'audio/fail-44-sc.mp3',
    // 'audio/fail-45.mp3',
    'audio/fail-46.mp3',
    'audio/fail-47.mp3',
    'audio/fail-48.mp3',
    'audio/fail-49.mp3',
    'audio/fail-50-violin.mp3',
    'audio/fail-51-violin.mp3',
    'audio/fail-52-violin.mp3',
    'audio/fail-53-violin.mp3',
    'audio/fail-54-violin.mp3',
    'audio/fail-55-violin.mp3',
    'audio/fail-56-violin.mp3',
    'audio/fail-57-violin.mp3',
    'audio/fail-58-violin.mp3',
    'audio/fail-59-violin.mp3',
    'audio/fail-60-violin.mp3',
    'audio/fail-61-violin.mp3',
    'audio/fail-62-violin.mp3',
    'audio/fail-63-violin.mp3',
    'audio/fail-64-violin.mp3',
    'audio/fail-65-violin.mp3',
    'audio/fail-66-violin.mp3',
    'audio/fail-67-violin.mp3',
    'audio/fail-68-violin.mp3',
    'audio/fail-69-violin.mp3',
    'audio/fail-70-violin.mp3',
    'audio/fail-71-violin.mp3',
    'audio/fail-72-digital.mp3',
    'audio/fail-73-buzz.mp3',
    'audio/fail-74.mp3',
    'audio/fail-75-bell-pipe.mp3',
    'audio/fail-76-err-delay.mp3',
    'audio/fail-77.mp3',
    // 'audio/fail-78-marimba.mp3',
    // 'audio/fail-79-marimba.mp3',
    // 'audio/fail-80-marimba.mp3',
    // 'audio/fail-81-marimba.mp3',
    // 'audio/fail-82-marimba.mp3',
    'audio/fail-83-buzz.mp3',
    // 'audio/fail-84-sci-fi.mp3',
    'audio/fail-85-cartoon.mp3',
    // 'audio/fail-86-futuristic.mp3',
    'audio/fail-87-digital-reset.mp3',
    'audio/fail-88-sci-fi.mp3',
    // 'audio/fail-89-xylofone.mp3',
    'audio/fail-90-sci-fi.mp3',
    'audio/fail-91.mp3',
    'audio/fail-92-sheeps.mp3',
    // 'audio/fail-93-trombone.mp3',
    'audio/fail-94-drums.mp3',
    'audio/fail-95-dogs.mp3',
    'audio/fail-96-ninja.mp3',
    'audio/fail-97-ball.mp3',
    'audio/fail-98-dissapoint.mp3',
    'audio/fail-99-o.mp3',
    // 'audio/fail-100-reverb.mp3',
    'audio/fail-101-cartoon.mp3',
    'audio/fail-102-percussive.mp3',
    'audio/fail-103-ukulele.mp3',
    'audio/fail-104-space.mp3',
    'audio/fail-105-bang.mp3',
    'audio/fail-106-voice.mp3',
    'audio/fail-107.mp3',
    'audio/fail-108-8bit.mp3',
    'audio/fail-109-lost.mp3',
    'audio/fail-110-8bit.mp3',
    'audio/fail-111-vintage-lost.mp3',
    'audio/fail-112.mp3',
    'audio/fail-113-brass.mp3',
    'audio/fail-114-group-voice.mp3',
    'audio/fail-115-jazzy.mp3',
    'audio/fail-116-sheep.mp3',
    'audio/fail-117.mp3',
    'audio/fail-118-ding.mp3',
    'audio/fail-119-ding.mp3',
    'audio/fail-120-group-voice.mp3',
    'audio/fail-121-group-voice.mp3',
    // 'audio/fail-122-trumplet.mp3',
    // 'audio/fail-123-trumplet.mp3',
    'audio/fail-124.mp3',
    'audio/fail-125.mp3',
    'audio/fail-126-digital.mp3',
    // 'audio/fail-127.mp3',
    'audio/fail-128.mp3',
    // 'audio/fail-129.mp3',
    // 'audio/fail-130.mp3',
    'audio/fail-131.mp3',
    // 'audio/fail-132-trumplet.mp3',
    // 'audio/fail-133-trumplet.mp3',
    'audio/fail-134.mp3',
    'audio/fail-135.mp3',
    'audio/fail-136.mp3',
    'audio/fail-137.mp3',
    'audio/fail-138.mp3',
    // 'audio/fail-139.mp3',
    'audio/fail-140.mp3',
    'audio/fail-150.mp3',
    'audio/fail-151.mp3',
    // 'audio/fail-152.mp3',
    // 'audio/fail-153.mp3',
    'audio/fail-154-trailer.mp3',
    'audio/fail-155-trailer.mp3',
    'audio/fail-156-trailer.mp3',
    'audio/fail-157-trailer.mp3',
    'audio/fail-158-trailer.mp3',
  ],
  click: [
    'audio/click-1.mp3',
    'audio/click-2.mp3',
    'audio/click-3.mp3',
    'audio/click-4-blow.mp3',
    'audio/click-5.mp3',
    'audio/click-6-photo.mp3',
    'audio/click-7-bell.mp3',
    'audio/click-8.mp3',
    'audio/click-9.mp3',
    'audio/click-10.mp3',
    'audio/click-11.mp3',
    'audio/click-12.mp3',
    'audio/click-13.mp3',
    'audio/click-14.mp3',
    'audio/click-15.mp3',
    'audio/click-16.mp3',
    'audio/click-17.mp3',
  ],
  load: [
    'audio/blues-1-intro.mp3',
    'audio/blues-2-intro-outro.mp3',
    'audio/blues-3-intro-outro.mp3',

    'audio/music-1-intro.mp3',
    'audio/music-2-intro.mp3',
    'audio/music-3-intro.mp3',
    'audio/music-4-intro.mp3',
    'audio/music-5-intro-china.mp3',
    'audio/music-6-intro-future.mp3',
    'audio/music-7-intro-atmospheric-logo.mp3',

    'audio/gong-1.mp3',
    'audio/gong-2.mp3',
    'audio/gong-3-big.mp3',
    'audio/gong-4.mp3',
    'audio/gong-5.mp3',
    'audio/gong-6.mp3',
    'audio/gong-7.mp3',

    'audio/load.mp3',
    'audio/load-2.mp3',
    'audio/load-3.mp3',
    'audio/load-4.mp3',
    'audio/load-5-mech.mp3',
    'audio/load-8-email.mp3',
    'audio/load-9-email.mp3',
    'audio/load-10-email.mp3',
    // 'audio/load-11-voice.mp3',
    'audio/load-12-mech.mp3',

    'audio/triller-1.wav',
    'audio/triller-2-metallic.wav',
    'audio/triller-3-futuristic.wav',
    'audio/triller-4-cartoon.wav',
    'audio/triller-5-cinematic.wav',
    'audio/triller-6-cinematic.wav',
    'audio/triller-7-cinematic.wav',
    'audio/triller-8-bass-long.wav',
    'audio/triller-10-ghost-horror.mp3',
  ],
  water: [
    'audio/water-1-drop.mp3',

    'audio/plop-1.mp3',
    'audio/plop-2-water-drop.mp3',
    'audio/plop-3.mp3',
    'audio/plop-4.mp3',
    'audio/plop-5-atmospheric.mp3',
    'audio/plop-6.mp3',
    'audio/plop-7.mp3',
  ],
}

const cache = {}

window.playRandomAudio = ({ type }) => {
  try {
    if (!type || !possibleAudio[type]) throw new Error(`Типа audio ${type} не существует`)

    const arr = possibleAudio[type]
    const randomSrc = arr[Math.floor(Math.random() * arr.length)]
    let audio

    if (!!cache[randomSrc]) {
      audio = cache[randomSrc]
    } else {
      audio = new Audio(randomSrc)
      audio.load()
      cache[randomSrc] = audio
    }

    audio.play()
  } catch (err) {
    console.log(err)
  }
}
